const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const revealObserver='IntersectionObserver' in window?new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');revealObserver.unobserve(e.target)}}),{threshold:0.08}):null;
function prepareReveal(){document.querySelectorAll('.reveal,.card,.section-top,.feature-card,.about-layout,.contact-row').forEach(el=>{if(el.dataset.revealBound)return;el.dataset.revealBound='1';if(revealObserver&&!reducedMotion.matches){el.classList.add('reveal-ready');revealObserver.observe(el)}else el.classList.add('is-visible')})}
reducedMotion.addEventListener('change',()=>{if(reducedMotion.matches)document.querySelectorAll('.reveal-ready').forEach(el=>el.classList.add('is-visible'))});
const chapters=['prologue','work','about','epilogue'].map(id=>document.getElementById(id));let scheduled=false;
function updateReading(){scheduled=false;const total=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading-progress span').style.transform=`scaleX(${Math.max(0,Math.min(1,scrollY/Math.max(1,total)))})`;let section=chapters[0];for(const el of chapters)if(el.getBoundingClientRect().top<innerHeight*.4)section=el;document.querySelectorAll('.chapter-dock a').forEach(a=>{if(a.hash==='#'+section.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}
window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateReading)}},{passive:true});window.addEventListener('resize',updateReading);prepareReveal();updateReading();
document.addEventListener('portfolio:render',()=>{prepareReveal();updateReading()});
document.querySelectorAll('[data-story]').forEach(b=>b.addEventListener('click',()=>{if(pages.length)openDetail(Number(b.dataset.story))}));
document.getElementById('filters').addEventListener('click',()=>{if(!reducedMotion.matches)document.getElementById('grid').animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:350,easing:'ease-out'})});
const viewer=document.getElementById('lightbox'),viewerImage=document.getElementById('lightbox-image'),stage=document.querySelector('.image-stage');let gallery=[],imageIndex=0;
function showImage(i){if(!gallery.length)return;imageIndex=(i+gallery.length)%gallery.length;viewerImage.src=gallery[imageIndex].href;viewerImage.alt=gallery[imageIndex].alt;document.getElementById('image-count').textContent=`${imageIndex+1} / ${gallery.length}`;stage.classList.remove('is-zoomed');document.getElementById('image-zoom').textContent=t('放大','Zoom');document.getElementById('image-prev').disabled=gallery.length<2;document.getElementById('image-next').disabled=gallery.length<2;stage.scrollTop=0;stage.scrollLeft=0}
function zoomImage(){const zoom=stage.classList.toggle('is-zoomed');document.getElementById('image-zoom').textContent=zoom?t('适应屏幕','Fit'):t('放大','Zoom')}
document.getElementById('image-prev').onclick=()=>showImage(imageIndex-1);document.getElementById('image-next').onclick=()=>showImage(imageIndex+1);document.getElementById('image-close').onclick=()=>viewer.close();document.getElementById('image-zoom').onclick=zoomImage;viewerImage.onclick=zoomImage;
viewer.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();showImage(imageIndex-1)}if(e.key==='ArrowRight'){e.preventDefault();showImage(imageIndex+1)}});
viewer.addEventListener('click',e=>{if(e.target===viewer){const b=viewer.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)viewer.close()}});
function enhanceDetail(){const body=document.getElementById('detail-body');const links=[...body.querySelectorAll('.media-grid a')].filter(a=>a.querySelector('img'));gallery=links.map(a=>({href:a.getAttribute('href'),alt:a.querySelector('img').alt}));links.forEach((a,i)=>a.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey)return;e.preventDefault();showImage(i);viewer.showModal()}));const records=pages.filter(p=>p.category!=='about'&&(active==='all'||p.category===active));const index=records.findIndex(p=>p.page===current);if(index<0)return;const nav=document.createElement('div');nav.className='project-switch';nav.innerHTML=`<button data-step="-1" ${index===0?'disabled':''}>${t('上一个项目','Previous project')}</button><span>${index+1} / ${records.length}</span><button data-step="1" ${index===records.length-1?'disabled':''}>${t('下一个项目','Next project')}</button>`;nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{const p=records[index+Number(b.dataset.step)];if(!p)return;body.querySelectorAll('video').forEach(v=>v.pause());openDetail(p.page,false);document.getElementById('detail').scrollTo({top:0,behavior:'instant'});document.getElementById('close').focus({preventScroll:true});if(!reducedMotion.matches)body.animate([{opacity:.25},{opacity:1}],{duration:250})});body.appendChild(nav)}
document.addEventListener('portfolio:detail',enhanceDetail);
